In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("customer.csv")

In [4]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [5]:
from sklearn.preprocessing import OrdinalEncoder

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.iloc[: , 2:4]
y = df.iloc[: , -1]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
X_train.head()

review education
46   Poor        PG
47   Good        PG
15   Poor        UG
9    Good        UG
16   Poor        UG

In [10]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [11]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: purchased, dtype: object

In [12]:
od = OrdinalEncoder()

In [13]:
od.fit(X_train)

OrdinalEncoder()

In [14]:
X_train = od.transform(X_train)

In [15]:
X_train

array([[2., 0.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [1., 1.]])

In [16]:
X_train = pd.DataFrame(X_train,columns = ['review','education'])

In [18]:
X_train.head(10)

review  education
0     2.0        0.0
1     1.0        0.0
2     2.0        2.0
3     1.0        2.0
4     2.0        2.0
5     0.0        0.0
6     0.0        1.0
7     2.0        1.0
8     0.0        1.0
9     0.0        2.0

In [19]:
X_train['review'].unique()  #  Average', 'Poor', 'Good

array([2., 1., 0.])

In [20]:
X_test = od.transform(X_test)
X_test

array([[0., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [1., 0.]])

In [21]:
X_train['review'].unique()

array([2., 1., 0.])

### Label encoding 

In [22]:
# Label encoding should be used for only dependent variable 

- This transformer should be used to encode target values, i.e. y, and not the input X

In [24]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [25]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: purchased, dtype: object

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
l = LabelEncoder()

In [28]:
l.fit(y_train)

LabelEncoder()

In [29]:
y_train_1 =  l.transform(y_train)

In [30]:
y_train_1.shape

(33,)

In [32]:
y_train[:10]

46     No
47    Yes
15     No
9     Yes
16    Yes
24    Yes
34     No
31    Yes
0      No
44     No
Name: purchased, dtype: object

In [33]:
y_train_1[:10]

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0])

In [34]:
pd.DataFrame(y_train_1 , columns=['target']).head()

target
0       0
1       1
2       0
3       1
4       1

### Test 

In [35]:
y_test_1 =  l.transform(y_test)

In [36]:
y_test_1.shape

(17,)

In [37]:
y_test[:10]

13     No
39     No
30     No
45    Yes
17    Yes
48    Yes
26     No
25     No
32    Yes
19    Yes
Name: purchased, dtype: object

In [38]:
y_test_1[:10]

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [39]:
pd.DataFrame(y_test_1 , columns=['target_1']).head()

target_1
0         0
1         0
2         0
3         1
4         1