### constant feartures means each observation has only same value and their variance will be = 0 , so we can remove those values definatelly 

In [5]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

In [6]:
df = pd.read_csv("dataset_1.csv")

In [7]:
df.head()

var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  var_9  var_10  ...  \
0      0      0    0.0   0.00    0.0      0      0      0      0       0  ...   
1      0      0    0.0   3.00    0.0      0      0      0      0       0  ...   
2      0      0    0.0   5.88    0.0      0      0      0      0       0  ...   
3      0      0    0.0  14.10    0.0      0      0      0      0       0  ...   
4      0      0    0.0   5.76    0.0      0      0      0      0       0  ...   

   var_292  var_293  var_294  var_295  var_296  var_297  var_298  var_299  \
0      0.0        0        0        0        0        0        0      0.0   
1      0.0        0        0        0        0        0        0      0.0   
2      0.0        0        0        3        0        0        0      0.0   
3      0.0        0        0        0        0        0        0      0.0   
4      0.0        0        0        0        0        0        0      0.0   

      var_300  target  
0      0.0000       0  
1      0.0000       0  
2  67772.7216       0  
3      0.0000       0  
4      0.0000       0  

[5 rows x 301 columns]

In [8]:
for i in df.columns:
    print(i , 'Null values :',df[i].isnull().sum())

var_1 Null values : 0
var_2 Null values : 0
var_3 Null values : 0
var_4 Null values : 0
var_5 Null values : 0
var_6 Null values : 0
var_7 Null values : 0
var_8 Null values : 0
var_9 Null values : 0
var_10 Null values : 0
var_11 Null values : 0
var_12 Null values : 0
var_13 Null values : 0
var_14 Null values : 0
var_15 Null values : 0
var_16 Null values : 0
var_17 Null values : 0
var_18 Null values : 0
var_19 Null values : 0
var_20 Null values : 0
var_21 Null values : 0
var_22 Null values : 0
var_23 Null values : 0
var_24 Null values : 0
var_25 Null values : 0
var_26 Null values : 0
var_27 Null values : 0
var_28 Null values : 0
var_29 Null values : 0
var_30 Null values : 0
var_31 Null values : 0
var_32 Null values : 0
var_33 Null values : 0
var_34 Null values : 0
var_35 Null values : 0
var_36 Null values : 0
var_37 Null values : 0
var_38 Null values : 0
var_39 Null values : 0
var_40 Null values : 0
var_41 Null values : 0
var_42 Null values : 0
var_43 Null values : 0
var_44 Null values :

### constant features removal 

In [9]:
from sklearn.feature_selection import VarianceThreshold

In [10]:
reg = VarianceThreshold()

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train.shape , X_test.shape

((33500, 300), (16500, 300))

In [15]:
reg.fit(X_train)

VarianceThreshold()

In [16]:
sum(reg.get_support())   # 258 feturess are not constant 

258

In [17]:
X_train.columns[reg.get_support()]

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8',
       'var_9', 'var_10',
       ...
       'var_289', 'var_290', 'var_291', 'var_292', 'var_293', 'var_295',
       'var_296', 'var_298', 'var_299', 'var_300'],
      dtype='object', length=258)

In [18]:
constant = X_train.columns[~reg.get_support()]

len(constant)

42

In [19]:
constant

Index(['var_14', 'var_23', 'var_33', 'var_34', 'var_44', 'var_61', 'var_66',
       'var_67', 'var_69', 'var_73', 'var_80', 'var_81', 'var_87', 'var_89',
       'var_92', 'var_97', 'var_99', 'var_112', 'var_113', 'var_120',
       'var_122', 'var_127', 'var_129', 'var_135', 'var_158', 'var_167',
       'var_171', 'var_178', 'var_180', 'var_182', 'var_183', 'var_195',
       'var_196', 'var_201', 'var_212', 'var_215', 'var_225', 'var_227',
       'var_248', 'var_287', 'var_294', 'var_297'],
      dtype='object')

In [20]:
for j in constant:
    print(j , X_train[j].unique())

var_14 [0]
var_23 [0]
var_33 [0]
var_34 [0]
var_44 [0]
var_61 [0]
var_66 [0]
var_67 [0]
var_69 [0]
var_73 [0]
var_80 [0]
var_81 [0]
var_87 [0]
var_89 [0.]
var_92 [0]
var_97 [0]
var_99 [0]
var_112 [0]
var_113 [0]
var_120 [0]
var_122 [0]
var_127 [0]
var_129 [0]
var_135 [0]
var_158 [0]
var_167 [0]
var_171 [0]
var_178 [0.]
var_180 [0.]
var_182 [0]
var_183 [0]
var_195 [0]
var_196 [0]
var_201 [0]
var_212 [0]
var_215 [0]
var_225 [0]
var_227 [0.]
var_248 [0]
var_287 [0]
var_294 [0]
var_297 [0]


In [21]:
X_train['var_171'].unique()

array([0], dtype=int64)

In [22]:
c = X_train.columns[reg.get_support()]

In [23]:
c

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8',
       'var_9', 'var_10',
       ...
       'var_289', 'var_290', 'var_291', 'var_292', 'var_293', 'var_295',
       'var_296', 'var_298', 'var_299', 'var_300'],
      dtype='object', length=258)

In [25]:
X_train = reg.transform(X_train)
X_test = reg.transform(X_test)

In [26]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [56]:
X_train = pd.DataFrame(X_train,columns=c)
X_test = pd.DataFrame(X_test,columns=c)

In [57]:
X_train.head()

var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  var_9  var_10  ...  \
0    0.0    0.0    0.0   2.79    0.0    0.0    0.0    0.0    0.0     0.0  ...   
1    0.0    0.0    0.0   0.00    0.0    0.0    0.0    0.0    0.0     0.0  ...   
2    0.0    0.0    0.0   2.79    0.0    0.0    0.0    0.0    0.0     0.0  ...   
3    0.0    0.0    0.0   2.76    0.0    0.0    0.0    0.0    0.0     0.0  ...   
4    0.0    0.0    0.0   2.88    0.0    0.0    0.0    0.0    0.0     0.0  ...   

   var_289  var_290  var_291  var_292  var_293  var_295  var_296  var_298  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   var_299  var_300  
0      0.0      0.0  
1      0.0      0.0  
2      0.0      0.0  
3      0.0      0.0  
4      0.0      0.0  

[5 rows x 258 columns]

In [58]:
X_train['var_1'].unique()

array([0., 9., 3., 6.])